use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
source 'http://bj.gitlab.cnlive.com/ios-team/CNLiveRepos.git'

platform :ios, '9.0'

target 'CNLiveCollectionModule_Example' do
  pod 'CNLiveCollectionModule', :path => '../'

  target 'CNLiveCollectionModule_Tests' do
    inherit! :search_paths

    
  end
end
